### ISSUE TITLE
对于 Android 15 构建的询问

### ISSUE THREAD

**Issue by Tseshongfeeshur** [stuartore/aosp-setup#2]
您好，请问有办法让这个脚本支持 Android 15 吗？
这是我使用 Rising OS 的 `fifteen` 分支时出现的报错内容：
```
=> sync source success.
=> Found device/xiaomi/psyche
including device/xiaomi/psyche/vendorsetup.sh
=> SKIP - source code is not Android 13
```

**Comment by stuartore** [comment]
没问题，近几天会更新

**Comment by Tseshongfeeshur** [comment]
好的，大佬辛苦啦🌹🌹

**Comment by Tseshongfeeshur** [comment]
想问您一下，您在您构建的 Android 14 版本的 Rising OS 的发布页面提到新的包需要使用 `fastboot update` 命令刷写，但由于我目前不太方便使用电脑，所以想通过 TWRP 执行该操作。我翻阅了压缩包内的 `fastboot-info.txt` 文件，其他行的含义我都大致明白，除了这一行：

```
update-super
```

我好像不明白如何在 TWRP 中执行等效操作，麻烦问下您有建议吗？

顺便说一句，我不太清楚您的 Android 14 版本的 Rising OS 需要什么底包，目前我准备刷写基于 Android 13 的 Hyper OS （最新） 作为底包，然后使用 TWRP 逐个刷写 Android 14 版本的 Rising OS 线刷包中的每个分区（除了上述提到的那一行操作我有点困惑）。

在次感谢您的解答。🌹🌹🌹

**Comment by stuartore** [comment]
Android 15好像要重新适配，目前好像没太多时间适配

参考[RisingOS](https://github.com/RisingTechOSS/android)文档，如果要构建针对RisingOS的卡刷包，使用`rise`或`rise b`均可以，如果你要修改脚本的内容，查找`rise fb`（仅修改这几个文字即可）:
```
# 修改为
rise
# 或
rise b
```

目前没有对vendor重新构建，原作者@xiaomi-psyche-development 相关信息可以在[这里](https://github.com/stuartore/device_xiaomi_psyche/blob/fourteen/vendorsetup.sh)找到（目前`source_xiaomi_psyche-devs`）:
```
source_xiaomi_sm8250-devs(){
	git_check_dir https://github.com/stuartore/device_xiaomi_psyche.git fourteen device/xiaomi/psyche
	git_check_dir https://github.com/xiaomi-sm8250-devs/android_device_xiaomi_sm8250-common.git lineage-21 device/xiaomi/sm8250-common
	git_check_dir https://github.com/stuartore/vendor_xiaomi_psyche fourteen lineage-21 vendor/xiaomi/psyche
	git_check_dir https://github.com/xiaomi-sm8250-devs/proprietary_vendor_xiaomi_sm8250-common.git lineage-21 vendor/xiaomi/sm8250-common
	git_check_dir https://github.com/Rocky7842/android_kernel_xiaomi_sm8250 lineage-21 kernel/xiaomi/sm8250
}

source_xiaomi_psyche-devs(){
	git_check_dir https://github.com/xiaomi-psyche-development/android_device_xiaomi_psyche lineage-21 device/xiaomi/psyche
 	git_check_dir https://github.com/xiaomi-psyche-development/android_device_xiaomi_sm8250-common lineage-21 device/xiaomi/sm8250-common
  	# sm8250 source tmp
   	# git_check_dir https://github.com/pachdomenic/android_device_xiaomi_sm8250-common lineage-21 device/xiaomi/sm8250-common
 	git_check_dir https://github.com/xiaomi-psyche-development/proprietary_vendor_xiaomi_psyche lineage-21 vendor/xiaomi/psyche
  	git_check_dir https://github.com/xiaomi-psyche-development/proprietary_vendor_xiaomi_sm8250-common lineage-21 vendor/xiaomi/sm8250-common
   	git_check_dir https://github.com/Rocky7842/android_kernel_xiaomi_sm8250 lineage-21 kernel/xiaomi/sm8250
}
```
对应的vendor版本号：`V816.0.6.0.TLDCNXM` （经过测试，此vendor在该source tree上表现一般，可能有电池不能更新电量的问题）

另外，在Android 14 QPR3后，存在相机、闪光灯占用问题，尽管尝试修复，目前参考了一些资料未解决

感谢提问🌹

**Comment by Tseshongfeeshur** [comment]
收到，我会去了解更多细节，祝您生活愉快！

**Comment by Tseshongfeeshur** [comment]
收到，我会去了解更多细节，祝您生活愉快！

**Comment by Tseshongfeeshur** [comment]
[#12](https://github.com/stuartore/device_xiaomi_psyche/issues/12#issuecomment-2442070742) 我注意到您似乎在[该 issue](https://github.com/stuartore/device_xiaomi_psyche/issues/12#issuecomment-2442070742) 提到了相机和闪光灯问题（该 issue 被标记为“已修复”），并且针对 Android 14 版本 Rising OS，您发布了两个版本（4.0 & 4.1），它们都没有修复该问题吗？您提到该问题“未解决”，那么该问题的表现是“相机完全不可用”还是“某些应用可用”？我已经在该仓库的分支仓库按照您的指点和官方文档的描述修改了构建命令，若摄像头与闪光灯通过某些方法可用，我会开始构建该 Rising OS 卡刷包。

与此同时我注意到开发者 [mickaelmendes50](https://github.com/mickaelmendes50/android_device_xiaomi_psyche) 在存储库中创建了设备树，而且这位开发者在 XDA 论坛上发布了自构建的 Android 14 版本 Paranoid Android，该 ROM 相机和闪光灯正常，请问他的设备树对修复上述问题有帮助吗？我需要怎么做？

非常抱歉占用了您的时间，以及感谢您对设备适配所做出的所有努力和尝试。😢🌹🌹

**Comment by stuartore** [comment]
我已发布RisingOS 6.0 Android 15开发预览版(vendor: `V816.0.10.0.TLDCNXM`)，感兴趣或开发请[点击此处](https://github.com/stuartore/device_xiaomi_psyche/releases/tag/risingos-v6-a15)访问。

感谢@stuartore @Flicker-Android-Devices  编译工具[点击此处](https://github.com/stuartore/aosp-setup)使用。🌹

**Comment by stuartore** [comment]
关于A14的问题，即使参考了一些commit，以及查看log未解决，不太会修，暂时搁置了。A15能不能用依然是个问题，因为目前没有投入大量时间去开发。

**Comment by Tseshongfeeshur** [comment]
好的，祝您生活愉快🙏🌹
